version: '3.8'

services:
  api:
    build: .
    container_name: consolidator-ai-api
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=consolidator_db
      - DB_USER=consolidator_admin
      - DB_PASSWORD=your_password_here
    extra_hosts:
      - "host.docker.internal:host-gateway" 