version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consolidator-ai-api
    ports:
      - "3005:3005"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 